version: "3.8"

services:
  frontend:
    image: mukeshsaini7/flutter-frontend:latest
    container_name: frontend
    restart: always
    networks:
      - app-network

  backend:
    image: mukeshsaini7/flutter-backend:latest
    container_name: backend
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"   # Public HTTP
      # - "443:443" # Uncomment later if you add SSL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
