version: "3.8"

services:
  frontend:
    image: mukeshsaini7/flutter-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"

  backend:
    image: mukeshsaini7/flutter-backend:latest
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    # env_file:
    #   - .env  # uncomment if you maintain backend env in a file
